### ISSUE TITLE
All points stay at max rank (apart from single goal point)

### ISSUE THREAD

**Issue by hamogor** [japanoise/dmap#1]
I'm relatively new to golang (specially interfaces) I've gotten quite far in implementing this package into my roguelike, after calling `Calc(g.Levels.Dungeons[g.Levels.Depth].SDown` (creating a point at the stair down position. All points on the Dmap stay at max rank (65525) and only the stair down position is set to 0. Rather than ranked by distance like in this article http://www.roguebasin.com/index.php?title=Dijkstra_Maps_Visualized#--_The_basics_-- 

Some help would be really appreciated as I'm using this implementation for my thesis. I'll try to provide sufficient amount of my code below

```
// My interface implementation
func (l Level) SizeX() int {
	return l.W
}

func (l Level) SizeY() int {
	return l.H
}

func (l Level) IsPassable(x, y int) bool {
	if l.Cells[x][y].Terrain == 0 {
		return true
	} else {
		return false
	}
}

func (l Level) OOB(x, y int) bool {
	if x >= 0 && y >= 0 {
		if x <= l.W && y <= l.H {
			return true
		}
	}
	return false
}
```

```
//Initialise DMap
func (g *game) initDMap() {
	d := BlankDMap(g.Levels.Dungeons[g.Levels.Depth], ManhattanNeighbours)
	d.Calc(g.Levels.Dungeons[g.Levels.Depth].SDown)
	g.Player.DMap = d
}
```

Do I need to `Recalc` every time the player moves? How can i draw a passable path from the player to the goal point?

Thanks in advance.

EDIT: Thought I should include my GetXY implementation
```
type position struct {
	X, Y  int
	point Point
}

func (p position) GetXY() (int,int) {
	return p.X, p.Y
}
```
`position` is the struct that my goals represent

**Comment by hamogor** [comment]
EDIT 2:
Well don't I feel silly.
I needed to switch the bools on `OOB`
```
func (l Level) OOB(x, y int) bool {
	if x >= 0 && y >= 0 {
		if x <= l.W && y <= l.H {
			return false
		}
	}
	return true
}
```

**Comment by japanoise** [comment]
Glad you're enjoying dmap, and thanks for bringing this to my attention, even if you've already solved the problem! I guess I need to document what this function does a little better...

**Comment by japanoise** [comment]
oh no, I misread your code, haha. No, I think this was the case of the bools getting mixed up as you said in your closing of the issue (happens to the best of us!). I prefer not to write bool funcs with an "if this, then return true, else return false" for this reason tbh. I'd rather write:

```golang
func (l Level) OOB(x, y int) bool {
	return !(x >= 0 && y >= 0 && x <= l.W && y <= l.H)
}
```

but that's personal preference. Once again, thank you for your interest in my project and I hope your RL development goes well!

**Comment by hamogor** [comment]
That's definately better! Thankyou!
